/// <summary>
/// MonoBehaviour事件类型
/// </summary>
public enum enMonoBehaviourEventType
{
//Awake
//FixedUpdate
//LateUpdate
//OnAnimatorIK
//OnAnimatorMove
//OnApplicationFocus
//OnApplicationPause
//OnApplicationQuit
//OnAudioFilterRead
//OnBecameInvisible
//OnBecameVisible
//OnCollisionEnter
//OnCollisionEnter2D
//OnCollisionExit
//OnCollisionExit2D
//OnCollisionStay
//OnCollisionStay2D
//OnConnectedToServer
//OnControllerColliderHit
//OnDestroy
//OnDisable
//OnDisconnectedFromServer
//OnDrawGizmos
//OnDrawGizmosSelected
//OnEnable
//OnFailedToConnect
//OnFailedToConnectToMasterServer
//OnGUI
//OnJointBreak
//OnLevelWasLoaded
//OnMasterServerEvent
//OnMouseDown
//OnMouseDrag
//OnMouseEnter
//OnMouseExit
//OnMouseOver
//OnMouseUp
//OnMouseUpAsButton
//OnNetworkInstantiate
//OnParticleCollision
//OnPlayerConnected
//OnPlayerDisconnected
//OnPostRender
//OnPreCull
//OnPreRender
//OnRenderImage
//OnRenderObject
//OnSerializeNetworkView
//OnServerInitialized
//OnTriggerEnter
//OnTriggerEnter2D
//OnTriggerExit
//OnTriggerExit2D
//OnTriggerStay
//OnTriggerStay2D
//OnValidate
//OnWillRenderObject
//Reset
//Start
//Update
}
