//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assets.Editor.StrayFog.EditorResxTemplete {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EditorResxTemplete {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EditorResxTemplete() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Assets.Editor.StrayFog.EditorResxTemplete.EditorResxTemplete", typeof(EditorResxTemplete).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 namespace StrayFogRunning
        ///{
        ///	/// &lt;summary&gt;
        ///	/// 资源磁盘映射枚举#EnumName#
        ///	/// &lt;/summary&gt;
        ///	public enum en#EnumName#
        ///	{#Enums#
        ///		#Name# = #HashCode#,#Enums#	
        ///	}
        ///} 的本地化字符串。
        /// </summary>
        internal static string AssetDiskMapingEnumTemplete {
            get {
                return ResourceManager.GetString("AssetDiskMapingEnumTemplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows Registry Editor Version 5.00
        /// 
        ///[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Folder\shell\DeleteSVN] @=&quot;Delete SVN Folders&quot;
        /// 
        ///[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Folder\shell\DeleteSVN\command]
        /// 
        ///@=&quot;cmd.exe /c \&quot;TITLE Removing SVN Folders in %1 &amp;&amp; COLOR 9A &amp;&amp; FOR /r \&quot;%1\&quot; %%f IN (.svn) DO RD /s /q \&quot;%%f\&quot; \&quot;&quot;
        /// 的本地化字符串。
        /// </summary>
        internal static string Cmd_ClearSvnTemplete {
            get {
                return ResourceManager.GetString("Cmd_ClearSvnTemplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 @echo on
        ///adb forward --remove-all
        ///pause
        ///adb kill-server
        ///pause
        ///adb start-server
        ///adb forward tcp:34999 localabstract:Unity-#DebugProfiler#
        ///pause 的本地化字符串。
        /// </summary>
        internal static string Cmd_DebugProfilerTemplete {
            get {
                return ResourceManager.GetString("Cmd_DebugProfilerTemplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 @echo on
        ///#DelCmd#del /s/q #Folder#\*.manifest#DelCmd#
        ///ping -n 3 127.1&gt;nul &amp; exit
        /// 的本地化字符串。
        /// </summary>
        internal static string Cmd_DeleteManifestTemplete {
            get {
                return ResourceManager.GetString("Cmd_DeleteManifestTemplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 taskkill /pid #Pid# /f
        ///&quot;#EngineExe#&quot; -projectPath &quot;#ProjectPath#&quot; -logFile &quot;#LogFile#&quot; -executeMethod &quot;#ExecuteMethod#&quot;
        ///ping -n 3 127.1&gt;nul &amp; exit 的本地化字符串。
        /// </summary>
        internal static string Cmd_ExecuteApplicationRestartMenu {
            get {
                return ResourceManager.GetString("Cmd_ExecuteApplicationRestartMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;#EngineExe#&quot; -quit -batchmode -projectPath &quot;#ProjectPath#&quot; -logFile &quot;#LogFile#&quot; -executeMethod &quot;#ExecuteMethod#&quot; 的本地化字符串。
        /// </summary>
        internal static string Cmd_ExecuteEngineMenu {
            get {
                return ResourceManager.GetString("Cmd_ExecuteEngineMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using StrayFogPlugins;
        ///using System.Collections.Generic;
        ///using UnityEngine;
        ///namespace StrayFogRunning
        ///{
        ///	/// &lt;summary&gt;
        ///	/// FMS状态机映射
        ///	/// &lt;/summary&gt;
        ///	public sealed class FMSMachineMaping
        ///	{	
        ///		#region MachineForLayer映射
        ///		/// &lt;summary&gt;
        ///		/// MachineForLayer映射
        ///		/// &lt;/summary&gt;
        ///		readonly static Dictionary&lt;int, List&lt;int&gt;&gt; mMachineForLayerMaping = new Dictionary&lt;int, List&lt;int&gt;&gt;() {#MACHINEFORLAYER#
        ///			{ (int)enFMSMachine.#MACHINE#,new List&lt;int&gt; { #LISTLAYER##LAYER#,#LISTLAYER# } },#MACHINEFORLAYE [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string EditorFMSMachineMapingScriptTemplete {
            get {
                return ResourceManager.GetString("EditorFMSMachineMapingScriptTemplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using StrayFogPlugins;
        ////// &lt;summary&gt;
        ////// #ClassName#
        ////// &lt;/summary&gt;
        ///public class #ClassName# : AbsScriptableObject
        ///{
        ///
        ///}
        /// 的本地化字符串。
        /// </summary>
        internal static string EdtiorCustomAssetNewAssetScriptTemplete {
            get {
                return ResourceManager.GetString("EdtiorCustomAssetNewAssetScriptTemplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] GrassDestabilizeShader {
            get {
                object obj = ResourceManager.GetObject("GrassDestabilizeShader", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] GreyShader {
            get {
                object obj = ResourceManager.GetObject("GreyShader", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] RippleWaterShader {
            get {
                object obj = ResourceManager.GetObject("RippleWaterShader", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 using StrayFogRunning;
        ///using System.Collections.Generic;
        ///namespace StrayFogRunning
        ///{
        ///	/// &lt;summary&gt;
        ///	/// #EntityName#实体
        ///	/// &lt;/summary&gt;
        ///	public partial class #ClassName#: AbsSQLiteDeterminantEntity
        ///	{
        ///		#Row#
        ///		/// &lt;summary&gt;
        ///		/// #Name#
        ///		/// &lt;/summary&gt;
        ///		public #Type# #Name# { get; private set; }#Row#
        ///	}
        ///} 的本地化字符串。
        /// </summary>
        internal static string SQLiteDeterminantEntityScriptTemplete {
            get {
                return ResourceManager.GetString("SQLiteDeterminantEntityScriptTemplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using StrayFogRunning;
        ///using System.Collections.Generic;
        ///namespace StrayFogRunning
        ///{
        ///    /// &lt;summary&gt;
        ///    /// SQLite表实体帮助类
        ///    /// &lt;/summary&gt;
        ///    public sealed partial class SQLiteEntityHelper
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// 实体名称映射
        ///        /// &lt;/summary&gt;
        ///        static readonly Dictionary&lt;int, string&gt; msrEntityNameMaping = new Dictionary&lt;int, string&gt;() {#EntityMaping#
        ///			{ typeof(#ClassName#).GetHashCode(),&quot;#TableName#&quot; },#EntityMaping#
        ///        };
        ///
        ///        /// &lt;summary&gt;
        ///        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string SQLiteEntityHelperExtendTemplete {
            get {
                return ResourceManager.GetString("SQLiteEntityHelperExtendTemplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using StrayFogRunning;
        ///using System.Collections.Generic;
        ///namespace StrayFogRunning
        ///{
        ///	/// &lt;summary&gt;
        ///	/// #EntityName#实体
        ///	/// &lt;/summary&gt;
        ///	public partial class #ClassName#: AbsSQLiteEntity
        ///	{
        ///		/// &lt;summary&gt;
        ///        /// PK键组
        ///        /// &lt;/summary&gt;
        ///        public override object[] pks { get { return new List&lt;object&gt;() { #PK##Name#,#PK#}.ToArray(); } }
        ///		#Properties#
        ///		/// &lt;summary&gt;
        ///		/// #Name#
        ///		/// &lt;/summary&gt;
        ///		public #Type# #Name# { get; private set; }#Properties#
        ///	}
        ///} 的本地化字符串。
        /// </summary>
        internal static string SQLiteEntityScriptTemplete {
            get {
                return ResourceManager.GetString("SQLiteEntityScriptTemplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] UIGraphicMaskFragmentShader {
            get {
                object obj = ResourceManager.GetObject("UIGraphicMaskFragmentShader", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] UIGraphicMaskVertexShader {
            get {
                object obj = ResourceManager.GetObject("UIGraphicMaskVertexShader", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 /// &lt;summary&gt;
        ////// UI窗口枚举
        ////// &lt;/summary&gt;
        ///public enum enUIWindow
        ///{
        ///#Windows#
        ///	#Name# = #Id#,
        ///#Windows#
        ///} 的本地化字符串。
        /// </summary>
        internal static string UIWindowEnumMapingTemplete {
            get {
                return ResourceManager.GetString("UIWindowEnumMapingTemplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using StrayFogPlugins;
        ///namespace StrayFogRunning
        ///{
        ///	/// &lt;summary&gt;
        ///	/// #NAME#
        ///	/// &lt;/summary&gt;
        ///	public class #NAME# : AbsUIWindowView
        ///	{
        ///
        ///	}
        ///} 的本地化字符串。
        /// </summary>
        internal static string UIWindowViewTemplete {
            get {
                return ResourceManager.GetString("UIWindowViewTemplete", resourceCulture);
            }
        }
    }
}
